info is:  [ { id: 110,
    description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p><span><em><strong><img src="https://usil.instructure.com/courses/31/files/855/preview?verifier=7kvXRYQjvL2qfgWcxGsgqdGgzyQAoUl8nTHQ9D3g" alt="FOROR.png" width="1134" height="198" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/855" data-api-returntype="File"></strong></em></span></p>\r\n<p><span><em><strong>Estimados Estudiantes:</strong></em></span></p>\r\n<p><span style="color: #333399;"><em>Bienvenidos al primer foro temático del curso.</em></span></p>\r\n<p><span style="color: #333399;"><em>Brinde 2 razones que sustenten la importancia de la comunicación. </em></span></p>\r\n<p><span style="color: #333399;"><em>Utilizar un máximo de dos párrafos (8 líneas como máximo).</em></span></p>\r\n<p><span style="color: #333399;"><em>Los primeros comentarios que se redacten hasta el martes 14 de agosto tendrán una mejor calificación.</em></span></p>\r\n<p><span style="color: #333399;"><em>El foro finaliza el sábado 18  de agosto a las 23:59 p.m.</em></span></p>\r\n<p><span style="color: #333399;"><em>No hay prórroga, tomar sus precauciones.</em></span></p>\r\n<p><span style="color: #333399;"><em>Saludos Cordiales y VIRTUALES!!!</em></span></p>',
    due_at: '2018-08-19T04:59:00Z',
    unlock_at: '2018-08-13T05:00:00Z',
    lock_at: '2018-08-19T04:59:59Z',
    points_possible: 20,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-08-16T19:25:59Z',
    updated_at: '2018-12-05T21:27:05Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 3,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: 0,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-08-19T04:59:59Z',
       can_view: true,
       asset_string: 'assignment_110' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImY3ZDNhYjBlLTMwMzktNDIyMi1iODY1LTczMjA2Njg0OWU5YyJ9.zMFllYmWuO1StTL9E5MCfsUhoFhXOwpqn_MwGXFKfSg',
    course_id: 31,
    name: 'Actividad de cierre: Foro temático del curso - Importancia de la comunicación',
    submission_types: [ 'discussion_topic' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: false,
    can_duplicate: true,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/110',
    discussion_topic: 
     { id: 38,
       title: 'Actividad de cierre: Foro temático del curso - Importancia de la comunicación',
       last_reply_at: '2018-08-19T01:35:27Z',
       created_at: '2018-08-13T16:38:26Z',
       delayed_post_at: null,
       posted_at: '2018-08-13T16:48:16Z',
       assignment_id: 110,
       root_topic_id: null,
       position: null,
       podcast_has_student_posts: false,
       discussion_type: 'side_comment',
       lock_at: null,
       allow_rating: false,
       only_graders_can_rate: false,
       sort_by_rating: false,
       is_section_specific: false,
       user_name: 'CORDOVA PISCOYA, PEDRO IVAN MARTIN',
       discussion_subentry_count: 19,
       permissions: [Object],
       require_initial_post: null,
       user_can_see_posts: true,
       podcast_url: null,
       read_state: 'read',
       unread_count: 4,
       subscribed: false,
       topic_children: [],
       group_topic_children: [],
       attachments: [],
       published: true,
       can_unpublish: false,
       locked: false,
       can_lock: true,
       comments_disabled: false,
       author: [Object],
       html_url: 'https://usil.instructure.com/courses/31/discussion_topics/38',
       url: 'https://usil.instructure.com/courses/31/discussion_topics/38',
       pinned: false,
       group_category_id: null,
       can_group: false,
       locked_for_user: true,
       lock_info: [Object],
       lock_explanation: 'Este tema fue bloqueado en 18 de ago de 2018 en 23:59.',
       message: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p><span><em><strong><img src="https://usil.instructure.com/courses/31/files/855/preview?verifier=7kvXRYQjvL2qfgWcxGsgqdGgzyQAoUl8nTHQ9D3g" alt="FOROR.png" width="1134" height="198" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/855" data-api-returntype="File"></strong></em></span></p>\r\n<p><span><em><strong>Estimados Estudiantes:</strong></em></span></p>\r\n<p><span style="color: #333399;"><em>Bienvenidos al primer foro temático del curso.</em></span></p>\r\n<p><span style="color: #333399;"><em>Brinde 2 razones que sustenten la importancia de la comunicación. </em></span></p>\r\n<p><span style="color: #333399;"><em>Utilizar un máximo de dos párrafos (8 líneas como máximo).</em></span></p>\r\n<p><span style="color: #333399;"><em>Los primeros comentarios que se redacten hasta el martes 14 de agosto tendrán una mejor calificación.</em></span></p>\r\n<p><span style="color: #333399;"><em>El foro finaliza el sábado 18  de agosto a las 23:59 p.m.</em></span></p>\r\n<p><span style="color: #333399;"><em>No hay prórroga, tomar sus precauciones.</em></span></p>\r\n<p><span style="color: #333399;"><em>Saludos Cordiales y VIRTUALES!!!</em></span></p>',
       todo_date: null },
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 18 de ago de 2018 en 23:59.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/assignments/110/submissions?zip=1',
    anonymize_students: false },
  { id: 113,
    description: '',
    due_at: null,
    unlock_at: '2018-08-21T18:00:00Z',
    lock_at: '2018-08-25T04:59:00Z',
    points_possible: 0,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-08-21T19:35:50Z',
    updated_at: '2018-08-24T21:17:07Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 5,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: null,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-08-25T04:59:00Z',
       can_view: true,
       asset_string: 'assignment_113' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImJkMTMzMjAyLTkwNTItNGEyNS1iNzljLWMwMWMzZTM3ZmYzNCJ9.8UHjvrhNBK-zFnuRHiTqkerF-yZWdw6cGosuhBu-UhA',
    course_id: 31,
    name: 'Lista de grupos para foros temáticos',
    submission_types: [ 'online_upload' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: false,
    can_duplicate: true,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/113',
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 24 de ago de 2018 en 23:59.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/assignments/113/submissions?zip=1',
    anonymize_students: false },
  { id: 146,
    description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p style="text-align: center;"><img src="https://usil.instructure.com/courses/31/files/850/preview?verifier=4KFKxP69QA6KNImEJh2AZhbTSGMsrKQIz3LFSZDB" alt="ACTIVIDAD-CALIFICADA.png" width="1110" height="194" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/850" data-api-returntype="File"></p>\r\n<p style="text-align: center;"><span style="color: #800000;"><strong>Tarea N°1:</strong></span></p>\r\n<p style="text-align: center;"><span style="color: #800000;"><strong>Primer Vídeo Reportaje </strong></span></p>\r\n<p> </p>\r\n<p><span style="color: #000080;"><strong>Estimados Estudiantes:</strong></span></p>\r\n<p><span style="color: #000080;">Estamos en la semana 3 del curso y es fundamental que revise los materiales de la sesión. Una vez revisada la Comunicación de masas y además conceptos de la semana 4 donde se desarrolla la Teoría Hipodérmica usted deberá elaborar un vídeo reportaje.</span></p>\r\n<p><span style="color: #000080;">El trabajo se sugiere elaborarlo de manera grupal, como máximo 7 integrantes. Si usted desea trabajar de manera individual puede hacerlo tranquilamente, sin embargo sugiero por la complejidad del trabajo, buscar conformar un grupo.</span></p>\r\n<p><span style="color: #000080;">Cabe precisar que el grupo puede ser tranquilamente el mismo que conformó para los foros temáticos.</span></p>\r\n<p><span style="color: #000080;">Una vez que conformó su grupo remita una lista al ítem tareas donde observará una carpeta con el título GRUPOS PARA PRIMER VÍDEO REPORTAJE.</span></p>\r\n<p><span style="color: #000080;">Luego debe elaborar un vídeo reportaje que debe tener una duración exacta de 10 minutos.</span></p>\r\n<p><span style="color: #000080;">La estructura del vídeo reportaje debe ser la siguiente:</span></p>\r\n<p><span style="color: #000080;"><strong>Primero</strong>: Presentar una claqueta (carátula del vídeo) con el Logotipo oficial de la Universidad, nombre de la Universidad, nombres y apellidos de los integrantes o autor del vídeo reportaje y nombre del docente: Pedro Iván Córdova Piscoya.</span></p>\r\n<p><span style="color: #000080;">El vídeo debe iniciar con una locución en off de 4 minutos donde puede desarrollar conceptos de Comunicación de Masas desarrollados en las diapositivas o archivos en PDF, igualmente pueden utilizar el texto de Marta Rizo titulado Comunicación interpersonal y nuevas formas de comunidad. Reflexiones sobre la comunicación posmasiva.</span></p>\r\n<p><span style="color: #000080;">También le puede servir para la locución en off los textos titulados Masa y Comunicación de Masas y El fin de los Medios de Comunicación de Masas. Ojo no se trata de copiar los contenidos, se trata de elaborar un resumen de las principales ideas y luego exponerlas en los 4 minutos de locución en off. Sugiero que la locución esté a cargo de un alumno con buena dicción y buen tono de voz. La locución en off puede ser “vestida” con imágenes de Google. Es decir la locución en off no debería aparecer con fondo negro, deben aparecer imágenes relacionadas al tema. Si desea utilizar vídeos sin audio puede hacerlo.</span></p>\r\n<p><span style="color: #000080;"><strong>Ojo,</strong> además puede incluir conceptos referidos a la Teoría Hipodérmica.</span></p>\r\n<p><span style="color: #000080;"><strong>Luego</strong> de esos 4 minutos de locución debe insertar una entrevista a un psicólogo o sociólogo o comunicador que no labore en la carrera de Comunicaciones de la USIL. Usted deberá entrevistarlo al referido profesional y preguntarle por ejemplo ¿Qué importancia tiene la Comunicación de Masas? Las preguntas deben buscar la opinión del entrevistado, no deberían ser un cuestionario para buscar definiciones, es decir no sugiero preguntar ¿Qué señala la Teoría Hipodérmica? Podría usted preguntar por ejemplo ¿Sigue vigente la Teoría Hipodérmica? La entrevista debe tener una duración de 6 minutos. Si la entrevista tiene una mayor duración sugiero editar.</span></p>\r\n<p><span style="color: #000080;">Ojo para efectos de la entrevista debe utilizar un Smartphone o su cámara personal, no se requieren equipos profesionales. Para la edición sugiero utilizar un simple programa denominado Windows Movie Maker. Sin embargo si usted utiliza complejos programas no está prohibido.</span></p>\r\n<p><span style="color: #000080;">Tras elaborar su vídeo de 10 minutos deberá subirlo a YouTube, colocarlo en público. Sugiero crear una cuenta expresamente para el curso o en todo caso utilizar una cuenta personal. Por favor es fundamental que todos titulen el vídeo en YouTube de la siguiente forma: COMUNICACIÓN DE MASAS – TEORÍA HIPODÉRMICA.</span></p>\r\n<p><span style="color: #000080;">Una vez que el vídeo esté en YouTube deben enviar el link del vídeo en un formato de Word con los nombres de los integrantes. El archivo deben enviarlo a la carpeta TAREAS donde encontrarán una carpeta denominada <strong>VÍDEO REPORTAJE N° 1.</strong></span></p>\r\n<p><span style="color: #000080;"><strong>La fecha final para la entrega es el viernes 7 de septiembre a las 23:59 p.m.</strong></span></p>\r\n<p><span style="color: #000080;">No hay prórroga, si usted envía a última hora puede tener problemas, recuerde que la tecnología puede fallar.</span></p>\r\n<p><span style="color: #000080;">Saludos Cordiales y VIRTUALES</span></p>\r\n<p> </p>\r\n<p><span style="color: #000080;"><strong>Prof. Pedro Iván Córdova Piscoya</strong></span></p>',
    due_at: '2018-09-08T04:59:59Z',
    unlock_at: '2018-08-24T05:00:00Z',
    lock_at: '2018-09-08T04:59:00Z',
    points_possible: 20,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-08-24T23:22:44Z',
    updated_at: '2018-10-17T16:10:06Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 6,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: 0,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-09-08T04:59:00Z',
       can_view: true,
       asset_string: 'assignment_146' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjI3ZjliYTk5LTU2MmYtNDg1Yy1hMzI5LWM1MGVkOTU2MDY3MiJ9.00KxIqo_sYunVpWrms9gx_0SphWuZ0v503_LWKLkXvw',
    course_id: 31,
    name: 'Tarea N°1: Primer Vídeo Reportaje ',
    submission_types: 
     [ 'online_text_entry',
       'online_url',
       'media_recording',
       'online_upload' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: false,
    can_duplicate: true,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/146',
    use_rubric_for_grading: false,
    free_form_criterion_comments: false,
    rubric: [ [Object], [Object], [Object], [Object], [Object] ],
    rubric_settings: 
     { id: 36,
       title: 'Rúbrica para la Evaluación de Vídeos',
       points_possible: 20,
       free_form_criterion_comments: false,
       hide_score_total: false,
       hide_points: false },
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 7 de sep de 2018 en 23:59.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/assignments/146/submissions?zip=1',
    anonymize_students: false },
  { id: 210,
    description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p><img src="https://usil.instructure.com/courses/31/files/1992/preview?verifier=b8wkqshE1CQ2drmHKiOWotaLBvYvJZzq5CizpCV6" alt="evaluacion.png" width="66" height="66" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/1992" data-api-returntype="File"></p>\n<p><span style="color: #003300;"><strong>Estimado estudiante:</strong></span></p>\n<p><span style="color: #003366;">Ha llegado el momento de evaluar parte de lo aprendido<strong><em> hasta la semana 5, a </em></strong>través de este control.</span></p>\n<p><span style="color: #003366;">A continuación se presentarán preguntas que deberá contestar. Recuerde que todas las preguntas sólo tienen una alternativa correcta.</span></p>\n<p><span style="color: #003300;"><strong><u>Importante:</u></strong></span></p>\n<ul>\n<li><span style="color: #003366;">Recuerde que solo tendrá un intento para realizar el control.</span></li>\n<li><span style="color: #003366;">Dispondrá de 20 minutos  para completar el control</span></li>\n</ul>\n<p style="text-align: center;"><strong><span style="color: #003366;">¡Muchos éxitos!</span></strong></p>',
    due_at: '2018-09-15T19:00:00Z',
    unlock_at: '2018-09-15T18:00:00Z',
    lock_at: '2018-09-15T19:00:00Z',
    points_possible: 20,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-09-11T16:11:21Z',
    updated_at: '2018-09-11T16:42:50Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 7,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: null,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-09-15T19:00:00Z',
       can_view: true,
       asset_string: 'assignment_210' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjVjZmQ2Y2Q2LTBhYjktNGM5Ni05N2IzLThhNDJjMWExZGJiOCJ9.cquKNfMqPIsBpTJEUW-8gq1nftucFeOuEj7oTj78s7o',
    course_id: 31,
    name: 'Control virtual',
    submission_types: [ 'online_quiz' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: true,
    can_duplicate: false,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/210',
    quiz_id: 53,
    anonymous_submissions: false,
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 15 de sep de 2018 en 14:00.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/quizzes/53/submissions?zip=1',
    anonymize_students: false },
  { id: 255,
    description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p><img></p>\n<p><span style="color: #000080;"><strong><img src="https://usil.instructure.com/courses/31/files/1992/preview?verifier=b8wkqshE1CQ2drmHKiOWotaLBvYvJZzq5CizpCV6" alt="evaluacion.png" width="71" height="71" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/1992" data-api-returntype="File">Estimado estudiante:</strong></span></p>\n<p><span style="color: #000080;">Ha llegado el momento de evaluar parte de lo aprendido <strong><em>hasta la semana 7, </em></strong><em>a </em>través de este control.</span></p>\n<p><span style="color: #000080;">A continuación se presentarán preguntas que deberá contestar. Recuerde que todas las preguntas sólo tienen una alternativa correcta.</span></p>\n<p><span style="color: #000080;"><strong><u>Importante:</u></strong></span></p>\n<ul>\n<li><span style="color: #000080;">Recuerde que solo tendrá un intento para realizar el control.</span></li>\n<li><span style="color: #000080;">Dispondrá de 20 minutos  para completar el control</span></li>\n</ul>\n<p><span style="color: #000080;"><strong>¡Muchos éxitos!</strong></span></p>',
    due_at: '2018-09-29T18:40:00Z',
    unlock_at: '2018-09-29T18:00:00Z',
    lock_at: '2018-09-29T18:40:00Z',
    points_possible: 20,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-09-25T23:23:24Z',
    updated_at: '2018-09-29T18:12:48Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 9,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: 0,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-09-29T18:40:00Z',
       can_view: true,
       asset_string: 'assignment_255' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImFkZDkwNDRlLWM3NTYtNDZiYi1iZTcxLTBlNzUwMjFhMDAwZCJ9.f98kCgV15YGXMfaRuG_BXpfbSWs0evmVKfoylYK7DTA',
    course_id: 31,
    name: 'Control virtual N°2',
    submission_types: [ 'online_quiz' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: true,
    can_duplicate: false,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/255',
    quiz_id: 117,
    anonymous_submissions: false,
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 29 de sep de 2018 en 13:40.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/quizzes/117/submissions?zip=1',
    anonymize_students: false },
  { id: 263,
    description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p><img src="https://usil.instructure.com/courses/31/files/850/preview?verifier=4KFKxP69QA6KNImEJh2AZhbTSGMsrKQIz3LFSZDB" alt="ACTIVIDAD-CALIFICADA.png" width="1134" height="198" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/850" data-api-returntype="File"></p>\r\n<p style="text-align: center;"><span style="font-size: 14pt; color: #800000;"><strong>Tarea N°2: Video Reportaje</strong></span></p>\r\n<p><strong><span style="color: #000080;">Estimados Estudiantes:</span></strong></p>\r\n<p><span style="color: #000080;">Estamos en la semana 8 del curso y es fundamental que revise los materiales de la sesión. Una vez revisada la Teoría del Framing y además conceptos de la semana 7 donde se desarrolla la Teoría de la Agenda Setting usted deberá elaborar un vídeo reportaje.</span></p>\r\n<p><span style="color: #000080;">El trabajo se sugiere elaborarlo de manera grupal, como máximo 7 integrantes. Si usted desea trabajar de manera individual puede hacerlo tranquilamente, empero sugiero por la complejidad del trabajo, buscar conformar un grupo.</span></p>\r\n<p><span style="color: #000080;">Cabe precisar que el grupo puede ser tranquilamente el mismo que conformó para los foros temáticos y para el primer reportaje.</span></p>\r\n<p><span style="color: #000080;">Una vez que conformó su grupo remita una lista al ítem tareas donde observará una carpeta con el título<strong> GRUPOS PARA SEGUNDO VÍDEO REPORTAJE.</strong></span></p>\r\n<p><span style="color: #000080;">Luego debe elaborar un vídeo reportaje que debe tener una duración exacta de 10 minutos.</span></p>\r\n<p><span style="color: #000080;">La estructura del vídeo reportaje debe ser la siguiente, primero presentar una claqueta (carátula del vídeo) con el Logotipo oficial de la Universidad, nombre de la Universidad, nombres y apellidos de los integrantes o autor del vídeo reportaje y nombre del docente: Pedro Iván Córdova Piscoya.</span></p>\r\n<p><span style="color: #000080;">El vídeo debe iniciar con una locución en off de 4 minutos donde puede desarrollar conceptos de la Teoría de la Agenda Setting y de la Teoría del Framing, desarrollados en las diapositivas o archivos en PDF, igualmente pueden utilizar los textos de Javier Odriozola Chené titulado “Cibermedios y agenda setting: la configuración de la agenda mediática internacional”.</span></p>\r\n<p><span style="color: #000080;">También le puede servir para la locución en off el texto de Alberto Ardévol-Abreu titulado “Framing o teoría del encuadre en comunicación”. Ojo no se trata de copiar los contenidos, se trata de elaborar un resumen de las principales ideas y luego exponerlas en los 4 minutos de locución en off. Sugiero que la locución esté a cargo de un alumno con buena dicción y buen tono de voz. La locución en off puede ser “vestida” con imágenes de Google. Es decir la locución en off no debería aparecer con fondo negro, deben aparecer imágenes relacionadas al tema. Si desea utilizar vídeos sin audio puede hacerlo.</span></p>\r\n<p><span style="color: #000080;">Luego de esos 4 minutos de locución debe insertar una entrevista a un psicólogo o sociólogo o comunicador que no labore en la carrera de Comunicaciones de la USIL, ojo de manera directa o de manera indirecta.</span></p>\r\n<p><strong><span style="color: #000080;">No está permitido entrevistar al mismo profesional del vídeo reportaje 1.</span></strong></p>\r\n<p><span style="color: #000080;">Usted deberá entrevistarlo al referido profesional y preguntarle por ejemplo ¿Qué importancia tienen los medios de comunicación al establecer una agenda de noticias? ¿Qué pasaría si no existieran esos medios? ¿Quién establece la agenda informativa? ¿Existe realmente la objetividad en el periodismo? Las preguntas deben buscar la opinión del entrevistado, no deberían ser un cuestionario para buscar definiciones, es decir no sugiero preguntar ¿Qué señala la Teoría del Framing? Podría usted preguntar por ejemplo ¿Usted realmente cree que los medios de comunicación encuadran las noticias, es decir resaltan un punto de la realidad en desmedro de otro? La entrevista debe tener una duración de 6 minutos. Si la entrevista tiene una mayor duración sugiero editar.</span></p>\r\n<p><span style="color: #000080;">Por favor el entrevistado debe ser una persona con experiencia y recomiendo colocar sus nombres completos y cargo en el que se desarrolla profesionalmente. Si el entrevistado no puede atenderlo físicamente usted puede entrevistarlo vía Skype, no obstante debe registrar en vídeo dicha entrevista.</span></p>\r\n<p><span style="color: #000080;">Ojo para efectos de la entrevista debe utilizar un Smartphone o su cámara personal, no se requieren equipos profesionales. Para la edición sugiero utilizar un simple programa denominado Windows Movie Maker. Sin embargo si usted utiliza complejos programas no está prohibido.</span></p>\r\n<p><span style="color: #000080;">Tras elaborar su vídeo de 10 minutos deberá subirlo a YouTube, colocarlo en público. Sugiero crear una cuenta expresamente para el curso o en todo caso utilizar una cuenta personal. Por favor es fundamental que todos titulen el vídeo en YouTube de la siguiente forma: LA TEORÍA DE LA AGENDA SETTING VERSUS LA TEORÍA DEL FRAMING.</span></p>\r\n<p><span style="color: #000080;">Una vez que el vídeo esté en YouTube deben enviar el link del vídeo en un formato de Word con los nombres de los integrantes. El archivo deben enviarlo a la carpeta TAREAS donde encontrarán una carpeta denominada VÍDEO REPORTAJE 2.</span></p>\r\n<p><strong><span style="color: #000080;">La fecha final para la entrega es el viernes 19 de octubre a las 23:59 p.m.</span></strong></p>\r\n<p><span style="color: #000080;">No hay prórroga, si usted envía a última hora puede tener problemas, recuerde que la tecnología puede fallar.</span></p>\r\n<p><span style="color: #000080;">Saludos Cordiales y VIRTUALES</span></p>\r\n<p><span style="color: #000080;">Prof. Pedro Iván Córdova Piscoya</span></p>\r\n<p> </p>\r\n<p> </p>',
    due_at: '2018-10-20T04:59:59Z',
    unlock_at: '2018-10-09T05:00:00Z',
    lock_at: '2018-10-20T04:59:59Z',
    points_possible: 20,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-10-09T15:08:32Z',
    updated_at: '2018-10-25T21:54:41Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 10,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: 0,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-10-20T04:59:59Z',
       can_view: true,
       asset_string: 'assignment_263' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjkwMWMzOTg3LTg0MjItNGE3OS1iZTc0LWQ2ZmUxMjc4N2MyNSJ9.H8dsyPJRt9cYaE0C_6gpuMJFReN-dYHsImO-YurzVHo',
    course_id: 31,
    name: 'Tarea N°2: Video Reportaje Grupal',
    submission_types: [ 'online_upload' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: false,
    can_duplicate: true,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/263',
    use_rubric_for_grading: false,
    free_form_criterion_comments: false,
    rubric: [ [Object], [Object], [Object], [Object], [Object] ],
    rubric_settings: 
     { id: 37,
       title: 'Rúbrica para la Evaluación de Vídeos',
       points_possible: 20,
       free_form_criterion_comments: false,
       hide_score_total: false,
       hide_points: false },
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 19 de oct de 2018 en 23:59.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/assignments/263/submissions?zip=1',
    anonymize_students: false },
  { id: 290,
    description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p><span style="color: #333399;"><strong><img src="https://usil.instructure.com/courses/31/files/1992/preview?verifier=b8wkqshE1CQ2drmHKiOWotaLBvYvJZzq5CizpCV6" alt="evaluacion.png" width="71" height="71" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/1992" data-api-returntype="File">Estimado estudiante:</strong></span></p>\n<p><span style="color: #333399;">Ha llegado el momento de evaluar parte de lo aprendido <strong><em>hasta la semana 11, </em></strong><em>a </em>través de este control.</span></p>\n<p><span style="color: #333399;">A continuación se presentarán preguntas que deberá contestar. Recuerde que todas las preguntas sólo tienen una alternativa correcta.</span></p>\n<p><span style="color: #333399;"><strong><u>Importante:</u></strong></span></p>\n<ul>\n<li><span style="color: #333399;">Recuerde que solo tendrá un intento para realizar el control.</span></li>\n<li><span style="color: #333399;">Dispondrá de 20 minutos  para completar el control</span></li>\n</ul>\n<p><span style="color: #333399;"><strong>¡Muchos éxitos!</strong></span></p>',
    due_at: '2018-11-03T18:20:00Z',
    unlock_at: '2018-11-03T17:00:00Z',
    lock_at: '2018-11-03T18:20:00Z',
    points_possible: 20,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-10-30T23:16:56Z',
    updated_at: '2018-11-02T16:22:45Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 12,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: 0,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-11-03T18:20:00Z',
       can_view: true,
       asset_string: 'assignment_290' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjhmNmQ4MGEyLTUxZjUtNDQ5ZC04ZWVmLTliNjkwNDY0MmNlNCJ9.kXHE-urjv2pUjRfnUMGRRZYQIXbA8RE7EEnXzoVvT1Y',
    course_id: 31,
    name: 'Control virtual N°3',
    submission_types: [ 'online_quiz' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: true,
    can_duplicate: false,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/290',
    quiz_id: 128,
    anonymous_submissions: false,
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 3 de nov de 2018 en 13:20.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/quizzes/128/submissions?zip=1',
    anonymize_students: false },
  { id: 299,
    description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_112860000000000001/attachments/865024/mobile.css"><p><span><strong><img src="https://usil.instructure.com/courses/31/files/1992/preview?verifier=b8wkqshE1CQ2drmHKiOWotaLBvYvJZzq5CizpCV6" alt="evaluacion.png" width="70" height="70" data-api-endpoint="https://usil.instructure.com/api/v1/courses/31/files/1992" data-api-returntype="File"><span style="color: #000080;">Estimado estudiante:</span></strong></span></p>\n<p><span style="color: #000080;">Ha llegado el momento de evaluar parte de lo aprendido <strong><em>hasta la semana 13, </em></strong><em>a </em>través de este control.</span></p>\n<p><span style="color: #000080;">A continuación se presentarán preguntas que deberá contestar. Recuerde que todas las preguntas sólo tienen una alternativa correcta.</span></p>\n<p> </p>\n<p><span style="color: #000080;"><strong><u>Importante:</u></strong></span></p>\n<ul>\n<li><span style="color: #000080;">Recuerde que solo tendrá un intento para realizar el control.</span></li>\n<li><span style="color: #000080;">Dispondrá de 20 minutos  para completar el control</span></li>\n</ul>\n<p> </p>\n<p><span style="color: #000080;"><strong>¡Muchos éxitos!</strong></span></p>',
    due_at: '2018-11-17T18:20:00Z',
    unlock_at: '2018-11-17T18:00:00Z',
    lock_at: '2018-11-17T18:20:00Z',
    points_possible: 20,
    grading_type: 'points',
    assignment_group_id: 60,
    grading_standard_id: null,
    created_at: '2018-11-13T19:36:32Z',
    updated_at: '2018-11-13T19:50:41Z',
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 13,
    grade_group_students_individually: false,
    anonymous_peer_reviews: false,
    group_category_id: null,
    post_to_sis: false,
    moderated_grading: false,
    omit_from_final_grade: false,
    intra_group_peer_reviews: false,
    anonymous_instructor_annotations: false,
    anonymous_grading: false,
    graders_anonymous_to_graders: false,
    grader_count: 0,
    grader_comments_visible_to_graders: true,
    final_grader_id: null,
    grader_names_visible_to_final_grader: true,
    allowed_attempts: -1,
    lock_info: 
     { lock_at: '2018-11-17T18:20:00Z',
       can_view: true,
       asset_string: 'assignment_299' },
    secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjkwNzZiMWFlLWZjN2ItNDVlMi1iN2ZhLWMzNzQxZTYyZTU5MyJ9.XNJP3cScdN-PJogowtuO3FlRpUkV_Lq-cJLg9xSlWLs',
    course_id: 31,
    name: 'Control virtual N°4',
    submission_types: [ 'online_quiz' ],
    has_submitted_submissions: true,
    due_date_required: false,
    max_name_length: 255,
    in_closed_grading_period: false,
    is_quiz_assignment: true,
    can_duplicate: false,
    original_course_id: null,
    original_assignment_id: null,
    original_assignment_name: null,
    workflow_state: 'published',
    muted: false,
    html_url: 'https://usil.instructure.com/courses/31/assignments/299',
    quiz_id: 134,
    anonymous_submissions: false,
    published: true,
    only_visible_to_overrides: false,
    locked_for_user: true,
    lock_explanation: 'Esta tarea fue bloqueada 17 de nov de 2018 en 13:20.',
    submissions_download_url: 'https://usil.instructure.com/courses/31/quizzes/134/submissions?zip=1',
    anonymize_students: false } ]